name: nerf_dart
version: 0.0.0
author: Kendal Harland <kendaljharland@gmail.com>
description: Automatically wrap C/C++ sources as Dart VM Native Extensions.
homepage: https://github.com/kharland/nerf_dart
executables:
 nerf
dependencies:
 petitparser:  '>=1.5.3 <2.0.0'
 args:
 yaml:
dev_dependencies:
 test: '>=0.12.1 <1.0.0'
