name: dartify
version: 0.0.3
author: Kendal Harland <kendaljharland@gmail.com>
description: Automatically wrap ANSI C source as a Dart Native Extension
homepage: https://github.com/kharland/dartify
executables:
 dartify:
dependencies:
 petitparser:  '>=1.4.3 <2.0.0'
 args: '>=0.13.2 <0.14.0'
dev_dependencies:
 test: '>=0.12.1 <1.0.0'
